#MS compiler: options : tested in Visual Studio 2013

PROG = try.exe
OBJECTS = main.obj readlines.obj getline.obj alloc.obj strcopy.obj quicksort.obj swap.obj strcomp.obj

!include ../../mk/makefile.mk